include(ExternalProject)

set(FAST_DOWNLOAD_DIR ${PROJECT_SOURCE_DIR}/external/)
set(FAST_EXTERNAL_BUILD_DIR ${PROJECT_BINARY_DIR}/external)
set(FAST_EXTERNAL_INSTALL_DIR ${PROJECT_BINARY_DIR}/external/install)
