file(GLOB installedSOs "${CMAKE_INSTALL_PREFIX}/fast/lib/*.so*")
foreach(SO ${installedSOs})
    if(SO MATCHES "^.*librealsense.*$")
    message("-- Setting runtime path of ${SO} and stripping..")
    execute_process(COMMAND strip -s ${SO} COMMAND patchelf --set-rpath "$ORIGIN/../lib" ${SO})
    else()
    message("-- Setting runtime path of ${SO}")
    execute_process(COMMAND patchelf --set-rpath "$ORIGIN/../lib" ${SO})
    endif()
endforeach()
