if(FAST_MODULE_Clarius)
  message(STATUS "-- Clarius ultrasound module enabled.")
  include(cmake/ExternalClarius.cmake)
    if(WIN32)
      list(APPEND LIBRARIES listen.lib)
    else()
      list(APPEND LIBRARIES liblisten.so)
    endif()
endif()
