if(FAST_MODULE_OpenVINO)
    message("-- Enabling Intel OpenVINO inference engine module")
    if(WIN32)
        set(InferenceEngine_BASE "C:/Program Files (x86)/IntelSWTools/openvino/inference_engine")
        set(InferenceEngine_DIR ${InferenceEngine_BASE}/share)
    else()
        set(InferenceEngine_BASE /opt/intel/openvino/inference_engine)
        set(InferenceEngine_DIR ${InferenceEngine_BASE}/share)
        if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
            set(IntelTBB ${InferenceEngine_BASE}/external/tbb/lib/libtbb_debug.so)
        else()
            set(IntelTBB ${InferenceEngine_BASE}/external/tbb/lib/libtbb.so)
        endif()
    endif()
    find_package(InferenceEngine REQUIRED)

endif()
