if(FAST_MODULE_WholeSlideImaging)
    message("-- Whole slide imaging module enabled")
    include(cmake/ExternalOpenSlide.cmake)
    set(TIFF_INCLUDE_DIRS ${FAST_EXTERNAL_BUILD_DIR}/qt5/src/qt5/qtimageformats/src/3rdparty/libtiff/)
    if(WIN32)
        list(APPEND LIBRARIES libopenslide.lib)
        list(APPEND FAST_INCLUDE_DIRS ${FAST_EXTERNAL_INSTALL_DIR}/include/openslide/)

        set(TIFF_LIBRARY libtiff.lib)
    else()
        find_package(OpenSlide REQUIRED)

        list(APPEND FAST_INCLUDE_DIRS ${OPENSLIDE_INCLUDE_DIRS})
        list(APPEND LIBRARIES ${OPENSLIDE_LIBRARIES})

        set(TIFF_LIBRARY libtiff.so)
     endif()
    message(STATUS "TIFF FOUND: ${TIFF_LIBRARY} ${TIFF_INCLUDE_DIRS}")
    list(APPEND FAST_INCLUDE_DIRS ${TIFF_INCLUDE_DIRS})
    list(APPEND FAST_LIBRARY_DIRS ${FAST_EXTERNAL_INSTALL_DIR}/plugins/imageformats/)
    list(APPEND LIBRARIES ${TIFF_LIBRARY})
endif()