if(FAST_MODULE_Clarius)
  message(STATUS "-- Clarius ultrasound module enabled.")
  include(cmake/ExternalClarius.cmake)
    if(WIN32)
      list(APPEND LIBRARIES cast.lib)
    else()
      list(APPEND LIBRARIES libcast.so)
    endif()
endif()
