name: FastPathology macOS 14 arm64

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  MACOSX_DEPLOYMENT_TARGET: 11.0

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew reinstall zlib
        brew install openslide pcre libomp
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}\
            -DCMAKE_OSX_ARCHITECTURES:STRING="arm64" \
            -DFAST_MODULE_OpenVINO=OFF \
            -DFAST_MODULE_Dicom=OFF \
            -DFAST_MODULE_WholeSlideImaging=ON \
            -DFAST_MODULE_OpenIGTLink=OFF \
            -DFAST_MODULE_Clarius=OFF \
            -DFAST_MODULE_TensorFlow=OFF \
            -DFAST_MODULE_HDF5=ON \
            -DFAST_MODULE_Plotting=ON \
            -DFAST_MODULE_Python=OFF \
            -DFAST_MODULE_RealSense=OFF \
            -DFAST_BUILD_EXAMPLES=OFF \
            -DFAST_BUILD_TESTS=ON \

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 4

    - name: Package
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target package -j 4
        mv ${{github.workspace}}/build/fast_*.tar.xz ${{github.workspace}}/build/fast_macos10.13_arm64.tar.xz

    - name: Upload archive package
      uses: actions/upload-artifact@v2
      with:
        name: Archive package (tar.xz)
        path: ${{github.workspace}}/build/fast_*.tar.xz
        if-no-files-found: error

    - name: Upload package to external repo release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_name: AICAN-Research/FAST-Pathology-dependencies
        repo_token: ${{ secrets.FAST_PATHOLOGY_PUSH_TOKEN  }}
        file: ${{github.workspace}}/build/fast_*.tar.xz
        asset_name: fast_macos10.13_arm64.tar.xz
        file_glob: true
        tag: v1.0.0
        overwrite: true
